/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.


*/

//TC : O(NLogN);
var findTheDifference = function (s, t) {
  s = s.split("").sort().join("");
  t = t.split("").sort().join("");
  console.log(s, t);

  for (let i = 0; i <= t.length - 1; i++) {
    if (s[i] == undefined || s[i] !== t[i]) {
      return t[i];
    }
  }
};
////////////////////////////////////////

var findTheDifference = function (s, t) {
  s = s.split("").sort();
  t = t.split("").sort();
  for (let i = 0; i <= t.length - 1; i++) {
    if (!s.includes(t[i])) {
      return t[i];
    }
    s[i] = "#";
  }
};
